name: mapico
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  audioplayers: ^5.2.0
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.9
  confetti: ^0.7.0
  sensors_plus: ^4.0.2
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/giris.png
    - .env
    - assets/balonPatlatmaSound/success.mp3
    - assets/balonPatlatmaSound/pop.mp3
    - assets/balonPatlatmaSound/wrong.mp3
    - assets/balonPatlatmaFlags/usa.png
    - assets/balonPatlatmaFlags/turkiye.png
    - assets/balonPatlatmaFlags/germany.png
    - assets/balonPatlatmaFlags/holland.png
    - assets/balonPatlatmaLokasyon/anitkabir.jpeg
    - assets/balonPatlatmaLokasyon/galata.jpeg
    - assets/balonPatlatmaLokasyon/kizKulesi.jpeg
    - assets/balonPatlatmaLokasyon/amsterdam_canal.jpeg
    - assets/balonPatlatmaLokasyon/windmill.jpeg
    - assets/balonPatlatmaLokasyon/brandenburg_gate.jpeg
    - assets/balonPatlatmaLokasyon/neuschwanstein.jpeg
    - assets/balonPatlatmaLokasyon/cologne_cathedral.jpeg
    - assets/balonPatlatmaLokasyon/white_house.jpeg
    - assets/balonPatlatmaLokasyon/statue_of_liberty.jpeg
    - assets/balonPatlatmaLokasyon/golden_gate.jpeg
    - assets/balonPatlatmaLokasyon/amsterdam_canal.jpeg
    - assets/balonPatlatmaLokasyon/keukenhof.jpeg
    - assets/balonPatlatmaLokasyon/windmill.jpeg
    - assets/balonPatlatmaLokasyon/brandenburg_gate.jpeg
    - assets/balonPatlatmaLokasyon/neuschwanstein.jpeg
    - assets/araçlar/character.png
    - assets/araçlar/lose.mp3
    - assets/araçlar/win.mp3
    - assets/araçlar/collect.mp3
    - assets/araçlar/plane_interior_usa.png
    - assets/araçlar/plane_interior_turkey.png
    - assets/araçlar/plane_background.png
    - assets/araçlar/nazar.png
    - assets/araçlar/kahve.png
    - assets/araçlar/hotdog.png
    - assets/araçlar/baseball.png
    - assets/araçlar/applepie.png
    - assets/cooking/domates.png
    - assets/cooking/ekmek.png
    - assets/cooking/et.png
    - assets/cooking/galeta-un.png
    - assets/cooking/kitchen-background.jpg
    - assets/cooking/kiyma.png
    - assets/cooking/limon.png
    - assets/cooking/marul.png
    - assets/cooking/sarimsak.png
    - assets/cooking/seker.svg
    - assets/cooking/sogan.png
    - assets/cooking/tarcin.png
    - assets/cooking/tavuk-gogsu.png
    - assets/cooking/tereyag.png
    - assets/cooking/un.svg
    - assets/cooking/yogurt.png
    - assets/cooking/yumurta.png
    - assets/cookinganimasyon/hamburger.gif
    - assets/cookinganimasyon/manti.gif
    - assets/cookingsound/fail.mp3
    - assets/cookingsound/tiklama.mp3
    - assets/cookingsound/tamamlandi.mp3
    - assets/cookinganimasyon/yemek.gif
